name: PR-build-test-deploy
on:
  push:
    branches: [main, feature/*]
env:
  ### VARIABLES GENERALES ###
  project_name: "mag-find-mutants-function"
  team: "mag"
  language: "go"
  handler: main
  memory: 128

jobs:
  install-dev-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

  build:
    runs-on: ubuntu-latest
    needs: install-dev-dependencies
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Run build
        run: go build .

  test-lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run vet & lint
        run: |
          go vet .

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Running Test
        run: |
          mkdir coverage
          go test -coverprofile=cover.out
          go tool cover -html=cover.out -o index.html
          mv cover.out coverage
          mv index.html coverage
      - name: Persist Data
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  sonarcloud:
    runs-on: ubuntu-20.04
    needs: [test-lint, test-coverage]
    name: SonarCloud
    steps:
      - uses: actions/checkout@v2
      - name: Restore Data
        uses: actions/download-artifact@v2
        with:
          name: coverage
          path: coverage
      - name: Current Branch
        shell: bash
        id: long-lived-branch
        run: |
          CURRENT_BRANCH=$(echo ${GITHUB_REF#refs/heads/})
          if [ "$CURRENT_BRANCH" != "main" ] && [ "$CURRENT_BRANCH" != "staging" ] && [ "$CURRENT_BRANCH" != "qa" ]
          then
            CURRENT_BRANCH="qa"
          fi
          echo "##[set-output name=branch;]$(echo ${CURRENT_BRANCH})"
          echo "Sonar Branch report => " ${CURRENT_BRANCH}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy-lambda:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/qa'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Lambda Function
        run: |
          GOOS=linux go build -o dist/main
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=${{env.project_name}} --zip-file=fileb://deploy.zip
