name: PR-build-test-deploy
on:
  push:
    branches: [main, feature/*]
env:
  ### VARIABLES GENERALES ###
  project_name: "mag-find-mutands-function"
  team: "mag"
  language: "go"
  files_compress: "src node_modules index.js package.json package-lock.json"
  handler: main
  memory: 128

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.x"
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      # - name: Run testing
      #   run: cd test && go test -v

  deploy-lambda:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/qa'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Lambda Function
          repository: jpaomat/mag-find-mutans-function
          tag_with_ref: true
